[package]
name = "spa"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
bitflags = "2.7.0"
cookie-factory = "0.3.3"
nom = "7.1.3"
